GtxApp/GtxApp/Models/Book.cs
using System;
using System.Collections.Generic;

namespace GtxApp.Models;

public partial class Book
{
    public int Id { get; set; }

    public string? Title { get; set; }

    public string? Author { get; set; }

    public string? Publisher { get; set; }

    public DateTime? Publisheddate { get; set; }

    public string? Isbn { get; set; }

    public int? Availablecopies { get; set; }

    public string? Ruser { get; set; }

    public DateTime? Registereddate { get; set; }

    public virtual ICollection<Borrowedbook> Borrowedbooks { get; set; } = new List<Borrowedbook>();
}

GtxApp/GtxApp/Controllers/BooksController.cs
using GtxApp.Data;
using GtxApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing.Template;

namespace GtxApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly qalinContext _db;
        public BooksController()
        {
            _db = new qalinContext();
        }
        public IActionResult Index()
        {
            if (TempData["msg"] != null)
            {
                ViewData["msg"] = TempData["msg"].ToString();
            }

            if (TempData["error"] != null)
            {
                ViewData["error"] = TempData["error"].ToString();
            }

            var _bookslist = _db.Books.OrderByDescending(m => m.Id).ToList();
            return View(_bookslist);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] //action verb
        public IActionResult Create([Bind("Title, Author, Publisher, Availablecopies")] Book model)
        {
            try
            {
                model.Registereddate = DateTime.Now;
                model.Ruser = "Zakaria";
                _db.Books.Add(model);
                _db.SaveChanges();
                TempData["msg"] = "New Book Added Successfully";

            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }

            return RedirectToAction("Index");

        }

        public IActionResult Edit(int id)
        {
            var found = _db.Books.Find(id);
            return View(found);
        }

        [HttpPost] //action verb
        public IActionResult Edit([Bind("Id, Title, Author, Publisher, Availablecopies")] Book model)
        {
            try
            {
                var _found = _db.Books.Find(model.Id);
                _found.Title = model.Title;
                _found.Author = model.Author;
                _found.Publisher = model.Publisher;
                _found.Availablecopies = model.Availablecopies;
                _db.Books.Update(_found);
                TempData["msg"] = "Book Edited Successfully";
                _db.SaveChanges();
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }

            return RedirectToAction("Index");

        }

        public IActionResult Delete(int id)
        {
            var _found = _db.Books.Find(id);
            return View(_found);
        }

        [HttpPost]
        public IActionResult Delete([Bind("Id, Title, Author")] Book model)
        {
            try
            {
                var _found = _db.Books.Find(model.Id);
                _db.Books.Remove(_found);
                _db.SaveChanges();
                TempData["msg"] = "Book Deleted Successfully";
                
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }

            return RedirectToAction("Index");

        }

    }
}

GtxApp/GtxApp/Views/Books/Create.cshtml
@using GtxApp.Models
@model Book

<h2>Create New Book</h2>

<div class="row">
    <div class="col-md-6">

        <form method="post" asp-controller="Books" asp-action="Create">
            <div class="form-group">
                <label>Title</label>
                <input type="text" asp-for="Title" class="form-control" placeholder="Enter Book Title" />
            </div>

            <br />
            <div class="form-group">
                <label>Author</label>
                <input type="text" asp-for="Author" class="form-control" placeholder="Enter Author Name" />
            </div>

            <br />
            <div class="form-group">
                <label>Publisher</label>
                <input type="text" asp-for="Publisher" class="form-control" placeholder="Enter Publisher Name" />
            </div>


            <br />
            <div class="form-group">
                <label># of Copies</label>
                <input type="number" asp-for="Availablecopies" class="form-control" placeholder="Enter Available Copies" />

            </div>

            <br />
            <button type="reset" class="btn btn-danger">Reset</button>
            <button type="submit" class="btn btn-primary">Submit</button>

        </form>

    </div>
    <div class="col-md-6"></div>
</div>

GtxApp/GtxApp/Views/Books/Delete.cshtml
@using GtxApp.Models
@model Book

<h2>Confirmation: Do you want to DELETE this Book ?</h2>

<div class="row">
    <div class="col-md-6">

        <form method="post" asp-controller="Books" asp-action="Delete">
            <input type="hidden" asp-for="Id" value="@Model.Id" />
            <div class="form-group">
                <label>Title</label>
                <input type="text" disabled asp-for="Title" value="@Model.Title" class="form-control" placeholder="Enter Book Title" />
            </div>

            <br />
            <div class="form-group">
                <label>Author</label>
                <input type="text" asp-for="Author" disabled value="@Model.Author" class="form-control" placeholder="Enter Author Name" />
            </div>

            

            <br />
            <a class="btn btn-success" asp-action="Index">Back</a>
            <button type="submit" class="btn btn-danger">Yes, Delete</button>

        </form>

    </div>
    <div class="col-md-6"></div>
</div>

GtxApp/GtxApp/Views/Books/Edit.cshtml
@using GtxApp.Models
@model Book

<h2>Edit Book</h2>

<div class="row">
    <div class="col-md-6">

        <form method="post" asp-controller="Books" asp-action="Edit">
            <input type="hidden" asp-for="Id" value="@Model.Id"/>
            <div class="form-group">
                <label>Title</label>
                <input type="text" asp-for="Title" value="@Model.Title" class="form-control" placeholder="Enter Book Title" />
            </div>

            <br />
            <div class="form-group">
                <label>Author</label>
                <input type="text" asp-for="Author" value="@Model.Author" class="form-control" placeholder="Enter Author Name" />
            </div>

            <br />
            <div class="form-group">
                <label>Publisher</label>
                <input type="text" asp-for="Publisher" value="@Model.Publisher" class="form-control" placeholder="Enter Publisher Name" />
            </div>


            <br />
            <div class="form-group">
                <label># of Copies</label>
                <input type="number" asp-for="Availablecopies" value="@Model.Availablecopies" class="form-control" placeholder="Enter Available Copies" />

            </div>

            <br />
            <button type="reset" class="btn btn-danger">Reset</button>
            <button type="submit" class="btn btn-primary">Submit</button>

        </form>

    </div>
    <div class="col-md-6"></div>
</div>

GtxApp/GtxApp/Views/Books/Index.cshtml
@using GtxApp.Models
@model List<Book>

<h3>Books</h3>

<div style="margin-top:50px;">

    @if (ViewData["msg"] != null)
    {
        <div class="alert alert-primary" role="alert">@ViewData["msg"].ToString()</div>
    }

    @if (ViewData["error"] != null)
    {
        <div class="alert alert-danger" role="alert">@ViewData["error"].ToString()</div>
    }

    <a class="btn btn-primary" asp-controller="Books" asp-action="Create">+ New Book</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Author</th>
                <th>Publisher</th>
                <th># of Copies</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @* the following is razor code block*@
            @{
                int counter = 1;
            }

            @foreach (var item in Model)
            {

                <tr>
                    <td>@counter</td>
                    <td>@item.Title</td>
                    <td>@item.Author</td>
                    <td>@item.Publisher</td>
                    <td>@item.Availablecopies</td>
                    <td>
                        <a class="btn btn-success" asp-controller="Books" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-danger" asp-controller="Books" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>

                counter++;

            }

        </tbody>
    </table>
</div>