GtxApp/GtxApp/Models/Customer.cs
using System;
using System.Collections.Generic;

namespace GtxApp.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string? Fullname { get; set; }

    public string? Address { get; set; }

    public string? Email { get; set; }

    public string? Mobile { get; set; }

    public string? Ruser { get; set; }

    public DateTime? Registereddate { get; set; }

    public virtual ICollection<Borrowedbook> Borrowedbooks { get; set; } = new List<Borrowedbook>();
}

GtxApp/GtxApp/Controllers/customersController.cs
using GtxApp.Data;
using GtxApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace GtxApp.Controllers
{
    public class customersController : Controller
    {
        private readonly qalinContext _context;

        public customersController()
        {
            _context = new qalinContext();
        }
        public IActionResult Index()
        {
            if (TempData["msg"] != null)
            {
                ViewData["msg"] = TempData["msg"].ToString();
            }

            if (TempData["error"] != null)
            {
                ViewData["error"] = TempData["error"].ToString();
            }

            //find customers from the db
            var _list = _context.Customers.OrderByDescending(k=>k.Id).ToList();

            return View(_list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("Fullname, Mobile, Address, Email")] Customer model)
        {
            try
            {
                model.Registereddate = DateTime.Now;
                model.Ruser = "Abuyahya";
                _context.Customers.Add(model);
                _context.SaveChanges();
                TempData["msg"] = "New Customer Created Successfully";

            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            //find customer
            Customer _found = _context.Customers.Find(id);
            return View(_found);

        }

        [HttpPost]
        public IActionResult Edit([Bind("Id, Fullname, Mobile, Address, Email")] Customer model)
        {
            try
            {
                Customer _found = _context.Customers.Find(model.Id);
                _found.Fullname = model.Fullname;
                _found.Address = model.Address;
                _found.Email = model.Email;
                _found.Mobile = model.Mobile;
                _context.Customers.Update(_found);
                _context.SaveChanges();
                TempData["msg"] = "Customer Data Edited Successfully";
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return RedirectToAction("Index");


        }

        public IActionResult Delete(int id)
        {
            Customer _found = _context.Customers.Find(id);
            return View(_found);
        }

        [HttpPost]
        public IActionResult Delete([Bind("Id")] Customer model)
        {
            try
            {
                Customer _found = _context.Customers.Find(model.Id);
                _context.Customers.Remove(_found);
                _context.SaveChanges();
                TempData["msg"] = "Customer Deleted Successfully";
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }

            return RedirectToAction("Index");


        }






    }
}

GtxApp/GtxApp/Views/customers/Create.cshtml
@using GtxApp.Models
@model Customer

<h2>Create New Customer</h2>


<div style="margin-top:50px;">
    <form method="post" asp-controller="customers" asp-action="Create">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Full Name</label>
                    <input asp-for="Fullname" type="text" class="form-control" placeholder="Enter Customer name" />
                </div>
                <br />
                <div class="form-group">
                    <label>Email</label>
                    <input asp-for="Email" type="email" class="form-control" placeholder="Enter Email" />
                </div>

                <br />
                <div class="form-group">
                    <label>Mobile</label>
                    <input asp-for="Mobile" type="text" class="form-control" placeholder="Enter Mobile +252xxxxxxxxx" />
                </div>

                <br />
                <div class="form-group">
                    <label>Address</label>
                    <textarea asp-for="Address" cols="5" rows="4" class="form-control"></textarea>
                </div>

                <br />
                <button type="reset" class="btn btn-danger">Reset</button>
                <button type="submit" class="btn btn-primary">Submit</button>



            </div>
            <div class="col-md-6">

            </div>
        </div>

    </form>
</div>

GtxApp/GtxApp/Views/customers/Delete.cshtml
@using GtxApp.Models
@model Customer

<h2>Confirmation: Do you want to DELETE this Customer?</h2>


<div style="margin-top:50px;">
    <form method="post" asp-controller="customers" asp-action="Delete">
        <div class="row">
            <div class="col-md-6">
                <input type="hidden" asp-for="Id" value="@Model.Id" />
                <div class="form-group">
                    <label>Full Name</label>
                    <input disabled asp-for="Fullname" value="@Model.Fullname" type="text" class="form-control" placeholder="Enter Customer name" />
                </div>
                <br />
                
                
                <button type="submit" class="btn btn-danger">Yes, Delete</button>



            </div>
            <div class="col-md-6">
            </div>
        </div>

    </form>
</div>

GtxApp/GtxApp/Views/customers/Edit.cshtml
@using GtxApp.Models
@model Customer

<h2>Edit Customer</h2>


<div style="margin-top:50px;">
    <form method="post" asp-controller="customers" asp-action="Edit">
        <div class="row">
            <div class="col-md-6">
                <input type="hidden" asp-for="Id" value="@Model.Id"/>
                <div class="form-group">
                    <label>Full Name</label>
                    <input asp-for="Fullname" value="@Model.Fullname" type="text" class="form-control" placeholder="Enter Customer name" />
                </div>
                <br />
                <div class="form-group">
                    <label>Email</label>
                    <input asp-for="Email" value="@Model.Email" type="email" class="form-control" placeholder="Enter Email" />
                </div>

                <br />
                <div class="form-group">
                    <label>Mobile</label>
                    <input asp-for="Mobile" value="@Model.Mobile" type="text" class="form-control" placeholder="Enter Mobile +252xxxxxxxxx" />
                </div>

                <br />
                <div class="form-group">
                    <label>Address</label>
                    <textarea asp-for="Address" value="@Model.Address" cols="5" rows="4" class="form-control"></textarea>
                </div>

                <br />
                <button type="reset" class="btn btn-danger">Reset</button>
                <button type="submit" class="btn btn-primary">Submit</button>



            </div>
            <div class="col-md-6">
            </div>
        </div>

    </form>
</div>

GtxApp/GtxApp/Views/customers/Index.cshtml
@using GtxApp.Models
@model List<Customer>


<h3>Customers List</h3>

<div style="margin-top:50px;">
    @if(ViewData["msg"]!= null)
    {
        <div class="alert alert-primary" role="alert">@ViewData["msg"].ToString()</div>
    }

    @if (ViewData["error"] != null)
    {
        <div class="alert alert-danger" role="alert">@ViewData["error"].ToString()</div>
    }
    <a asp-controller="customers" asp-action="Create" class="btn btn-primary">+ Add Customer</a>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @* this is code block *@
            @{
                int counter = 1;
            }

            @foreach(var item in Model)
            {
                <tr>
                    <td>@counter</td>
                    <td>@item.Fullname</td>
                    <td>@item.Email</td>
                    <td>@item.Mobile</td>
                    <td>
                        <a class="btn btn-success" asp-controller="customers" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-danger" asp-controller="customers" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                counter++;
                
            }
        </tbody>
    </table>
</div>